
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8085
spring:
  application:
    name: service-zuul

zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: consumber-ribbon
    api-b:
      path: /api-b/**
      serviceId: consumer-feign


